# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85323cdf97e00d2a12805adb44c77e818f13e8264d537b380c91fe416bfe3424969f2c0a4c92805dee2db605e00cd0f600141f62ecc39ea20b6ad7c1c40c15fb

test:
  secret_key_base: 578f2e8bef382bc9ff673ea3e69acb8644c5f549f909a7fb00a15fa73815aceb1be1143acc475503fe09e0a0f66a185f2a56aaef208cc199c8cee9881f00ce96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
